

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const REQUEST_PRODUCT = 'REQUEST_PRODUCT'
export const SET_AUTH_USER = 'SET_AUTH_USER'
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE'
export const FETCH_USER_PRODUCTS_SUCCESS = 'FETCH_USER_PRODUCTS_SUCCESS'

